server:
  port: 8081
management:
  server:
    port: 8089

camel:
  component:
    metrics:
      enabled: true
  servlet:
    mapping:
      context-path: /agent/*

spring:
  application:
    name: cagent