
deployment:
  name: cagent

cluster:
    role:
      binding:
        name: cagent-reader-binding
      name: cagent-reader

image:
  repository: surisoft/cagent:2.0.0
  pullPolicy: Always

cagent:
  namespace: test-agent
  consulHost: http://host.docker.internal:8500
  consulToken:  
  executorInitialDelay: 5
  executorExecutionInterval: 5
  serviceAccountName: capi
  discoverServices: false
  defaultLogLevel: DEBUG
  upgrade: up39.github

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 60
