name: cagent
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v1.4.4
      with:
        java-version: 21
    - uses: actions/checkout@v3.5.3
    - name: Docker login
      run: |
          docker login -u surisoft -p ${{ secrets.DOCKER_HUB_PWD }}
    - name: Build and push multi-platform image
      run: |
        docker buildx create --use
        docker buildx build . \
          --platform linux/amd64,linux/arm64 \
          --build-arg "CAGENT_VERSION=${{ env.RELEASE_VERSION }}" \
          --file Dockerfile \
          --tag surisoft/cagent:${{ env.RELEASE_VERSION }} \
          --tag surisoft/cagent:latest \
          --push